rogchap/v8go

CHANGELOG.md, README.md, cgo.go, v8go.cc, v8go.h
As per title; includes formatting the current C++ files: v8go.h|cc
=> Add clang-format for C files

CHANGELOG.md, errors_test.go, v8go.cc, v8go.h, value.go, value_test.go
This will enable getting of richer data types from the v8 value struct than just currently `string`
All the basic `ToXXX` methods have been implemented as defined here: 
https://v8.github.io/api/head/classv8_1_1Value.html#a838af7d16f0ce87b4411beb178383db4
However `ToBigInt()` and `ToObject()` have NOT yet been implemented. The reason is that `Object` represents everything that is not a primitive type: eg. Functions, Objects, Promises, Dates, Regex etc. Implementing all of the `Object` type would make this PR too large, and take quite a bit of time to implement.
Was hoping to include this PR in the next release, which already has a number of features people are waiting for to be released.
As such, I think it's best to un-export these methods (to not break the public API), get this PR …
=> Add (Basic) getter methods for the v8 value struct

CHANGELOG.md, context.go, context_test.go, export_test.go, function_template.go, function_template_test.go, isolate.go, isolate_test.go, object_template.go, template.go, v8go.cc, v8go.h, value.go, value_test.go
Basic `FunctionTemplate` support, which allows global functions that callback to Go functions:
```go
iso, _ := v8go.NewIsolate()
global, _ := v8go.NewObjectTemplate(iso)
printfn, _ := v8go.NewFunctionTemplate(iso, func(info *v8go.FunctionCallbackInfo) *v8go.Value {
fmt.Printf("%+v\n", info.Args())
return nil
})
global.Set("print", printfn, v8go.ReadOnly)
ctx, _ := v8go.NewContext(iso, global)
ctx.RunScript("print('foo', 'bar', 0, 1)", "")
// Output:
// [foo bar 0 1]
```
Due to the complexities of Go -> C -> Go there are two registries:
1) Callback registry attached to the Isolate
2) A global registry for the Context
To make sure that created Contexts can be GC'd we have a register/deregister surrounding script execution; other wise a `map[int]*Context` would never GC
=> Function Templates with callback functions in Go

LICENSE, cgo.go, context.go, context_test.go, errors.go, errors_test.go, export_test.go, function_template.go, function_template_test.go, isolate.go, isolate_test.go, json.go, json_test.go, object_template.go, object_template_test.go, template.go, v8go.cc, v8go.go, v8go.h, v8go_test.go, value.go, value_test.go
Updates the LICENSE for v8go to be **3 Clause BSD** from MIT
BSD has a minute difference to MIT and are basically "the same" (but I'm not a lawyer so... 🤷‍♂️)
This keeps the license in-line with the V8 library (and Go itself) that also has a the 3 Clause BSD license.
=> BSD-style licence

CHANGELOG.md, context.go, json.go, json_test.go, object.go, object_template.go, object_template_test.go, object_test.go, v8go.cc, v8go.h, value.go, value_test.go
Basic casting of a Value to an Object (`val.AsObject()`) as well as converting Value to an Object (`val.Object()`)
Only covers a small subset of the Object API as described here: https://v8.github.io/api/head/classv8_1_1Object.html
Also includes converting an `ObjectTemplate` to an `Object` with a given Context, and retrieving the Global Object from a Context.
This allows for things like this at runtime: 
```go
iso, _ := v8go.NewIsolate()
obj, _ := v8go.NewObjectTemplate(iso)
ctx, _ := v8go.NewContext(iso, obj)
global := ctx.Global()
console, _ := v8go.NewObjectTemplate(iso)
logfn, _ := v8go.NewFunctionTemplate(iso, func(info *v8go.FunctionCallbackInfo) *v8go.Value {
fmt.Println(info.Args()[0])
return nil
})
console.Set("log", logfn)
consoleObj, _ := console.NewInstance(ctx) …
```
=> Extend Value into the Object type

CHANGELOG.md, context.go, context_test.go, function_template.go, v8go.cc, v8go.h, value.go
See https://gophers.slack.com/archives/C01FW4CR5D2/p1613070695024600 for full details.
TLDR; When returning a value to Go from a V8 Context the Persistent Value storage was not being Reset correctly, and also stopped the V8 Context from being GC'd. Added memory issues where also caused by Go's GC not firing fast enough as it does not understand the memory allocated to the objects held by pointers in the C world.
This fix, tracks Values returned from the context, and when the Context is closed (either manually or by the Go GC) it will also reset all those values correctly.
=> Release value memory on context close

v8go.cc, v8go.go, v8go.h, v8go_test.go
As requested by @kuoruan
https://github.com/rogchap/v8go/pull/76#issuecomment-789490323
=> Allow setting/unsetting of V8 feature flags

CHANGELOG.md, function.go, function_test.go, v8go.cc, v8go.h, value.go, value_test.go
=> Support for invoking a function value

.github/workflows/test.yml, .github/workflows/v8build.yml, README.md, cgo.go, deps/build.py, deps/windows_x86_64/.gitattributes, deps/windows_x86_64/0000-add-mingw-main-code-changes.patch, deps/windows_x86_64/0001-add-mingw-toolchain.patch, deps/windows_x86_64/0002-fix-mingw-unwind-tables.patch, deps/windows_x86_64/README.md, deps/windows_x86_64/vendor.go, deps/windows_x86_64/zlib.gn, v8go.cc
This PR adds the bits required to provide a prebuilt static V8 library on Windows, offering basically the same level of end user convenience as on Linux/Mac (i.e. not having to deal with a dozen DLLs in a distribution).
Existing Windows builds using v8go should not break, the change merely renders the need to package additional files with the executable unnecessary.
=> Build for static V8 library on Windows

.github/workflows/test.yml
@rogchap Missed that the FOSSA step would break the Windows build in #102, sorry.
If the scan doesn't have to run on Windows and can be skipped, feel free to close this PR (and just copy the skip condition from line 43).
Otherwise the separate step using Powershell is required, because the FOSSA install script doesn't work in Git bash on Windows.
=> Fix FOSSA scan on Windows

function_template.go, function_template_test.go, v8go.cc, v8go.h
This allows you to instantiate a FunctionTemplate for a context.
=> FunctionTemplate::GetFunction

CHANGELOG.md, context.go, function.go, function_test.go, v8go.cc, v8go.h
I was trying to do something like `new Error(message)` from Go code, but didn't see a way of using the javascript `new` operator.
It looks like v8::Function::NewInstance is the function we need for doing this, so I added a corresponding function to the v8go API.
=> Add Function.NewInstance to expose the corresponding V8 function

CHANGELOG.md, deps/build.py
I was getting an `ReferenceError: Intl is not defined` error from trying to use the Intl JS namespace which is a builtin feature of v8 (https://v8.dev/blog/intl).  I found this wasn't working because v8go was building with `v8_enable_i18n_support=false`.
Removing `v8_enable_i18n_support=false` from the build configuration and rebuilding solved the problem for me.
As instructed in the README.md, I didn't add any built binaries to the commit I pushed.  I don't have access to run the "V8 Build" Github Action, so that still needs to be done to update the pre-built binaries in order to actually fix this issue.
=> Build v8 with i18n support

CHANGELOG.md, README.md, context.go, context_test.go, function_template.go, function_template_test.go, function_test.go, isolate_test.go, object_template.go, object_template_test.go, object_test.go, promise.go
Fixes #108
The above issue linked to https://github.com/rogchap/v8go/pull/118#discussion_r619480410 where it was decided that `panic` may be more appropriate and idiomatic Go code in certain cases
Specifically, this makes sense when:
* there is no underlying error in the v8 API used
* any error can be equivalently checked in the caller
* the error typically represents a bug in the caller
As such, I removed error from the type signature of:
* Context.Isolate
* NewObjectTemplate
* NewFunctionTemplate
=> Avoid error in type signature for Context.Isolate, NewObjectTemplate & NewFunctionTemplate

README.md, deps/build.py
cc @genevieve 
While @ofuerst was looking into adding support for v8::ScriptCompiler::CompileUnboundScript, he encountered crashes which weren't easy to debug using the pre-build v8go libv8.  I tried to build v8 with debugging information to get a C++ backtrace to help debug the problem, although this involved modifying deps/build.py and also wasn't very clear to someone not already used to debugging crashes from cgo integrations.  Note that the problem ended up being caught by V8 debug checking.
I've modified deps/build.py to include line number information when that script is used with the `--debug` flag.
I've also documented the steps I used get a C++ backtrace using a debugger.  I tried out the steps on MacOS with lldb and Ubuntu with both lldb and gdb.  Although, I found that …
=> Include line number information in debug builds of v8

CHANGELOG.md, function_template.go, v8go.cc, v8go.h, value.go, value_test.go
When comparing objects, it would be useful to be able to test that the objects are the same and don't just have the same data, so I exposed v8::Value::SameValue
=> Add value.SameValue(otherValue) function

CHANGELOG.md, isolate.go, v8go.cc, v8go.h, value.go, value_test.go
Builds on #162 
cc @genevieve 
Currently, there is no simple way of getting `null` or `undefined` JS values from v8go.  There are workarounds like running a script to get these values, but this shouldn't be necessary.
For instance, this would be useful in #160 for explicitly passing the `undefined` value as an explicit function call receiver
=> Expose null and undefined constant values

CHANGELOG.md, function.go, object.go, object_test.go, v8go.cc, v8go.h
An extension of #159 to fix #156
https://github.com/rogchap/v8go/pull/159#issuecomment-910678699
Builds on #162
=> Support calling a method on an object.

CHANGELOG.md, README.md, context.go, context_test.go, errors_test.go, function_template_test.go, function_test.go, isolate.go, isolate_test.go, json_test.go, object_template_test.go, object_test.go, promise_test.go, v8go_test.go, value_test.go
Neither [v8::Isolate::New](https://v8.github.io/api/head/classv8_1_1Isolate.html#ab6accf94a5a897fcc1220ab2c049e502) or [v8::Context::New](https://v8.github.io/api/head/classv8_1_1Context.html#aa06c74ca4f5d1aa63449b814825300eb) have a possible error in their return type, but v8go does for NewIsolate and NewContext even though they never return an error. 
NewIsolate and NewContext have a `// TODO: [RC] catch any C++ exceptions and return as error` comment, yet the [v8go's API Design doc](https://github.com/rogchap/v8go/blob/1c2cf245a0018ee39186e4c193a3fb427069e351/deps/include/APIDesign.md#ecmascript-like-capabilities) now acknowledges that
> V8's C++ code doesn't use C++ exceptions.
This is a [part of the Google's C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Exceptions …
=> Removed error return value from NewIsolate & NewContext

CHANGELOG.md, function.go, function_template_test.go, function_test.go, object.go
(cherry picked from commit 991ab091d967512721296e380a731efa08c9f85c)
Fixes https://github.com/rogchap/v8go/issues/156
The v8go library is implicitly passing `undefined` as the receiver when executing a function `Call`. To make this configurable, as shown in this PR, it would be a breaking change to the v8go api for the function object. This change ensures the explicit passing of a receiver to a function and avoid additional confusion around the fact that functions obtained from an object are not bound to the object they are obtained from. If we want to avoid the breaking change, we could instead expose something on the v8go object type called `MethodCall` which would ensure the proper execution a function/method with the object as it's receiver and avoid code like:
```
respVal, _ := …
```
=> Function Call should support recv argument

CHANGELOG.md, isolate.go, isolate_test.go, v8go.cc, v8go.h
Introduce isolate's `IsExecutionTerminating()` to check if an execution is still terminating
=> Introduce isolate's IsExecutionTerminating to wait for termination

README.md, context_test.go, errors_test.go, function_template_test.go, function_test.go, isolate_test.go, json_test.go, object_template_test.go, object_test.go, promise_test.go, v8go_test.go, value_test.go
The `go` suffix makes sense in the context of the repository name, since it otherwise wouldn't be obvious from the url that it refers to Go bindings for v8.  However, when the library is imported, the `go` suffix becomes redundant since it is already in the context of go code.
As mentioned in the Go [Package names](https://go.dev/blog/package-names) blog post
> Good package names are short and clear.
So recommend importing the package as `v8` instead seems like better guidance for users of the library, without require a breaking change.
Note that we may want to consider moving the package to a `v8` subfolder in the repo to instead import using `import "rogchap.com/v8go/v8"`.  However, let's start with the recommendation, which if followed, will only require changes to the import lines if …
=> Recommend importing as v8 instead of the default of v8go

.github/workflows/test.yml
cc @genevieve 
It can be useful to enable Github Actions in a fork to test a branch on CI before opening a PR or without pushing debugging code to the PR branch.  However, when doing that, the "Scan and upload FOSSA data" CI steps will fail because they don't have the corresponding github secret.
The same problem comes up for anyone temporarily maintaining a fork of this repo to unblock themselves while they wait for a change to get accepted and merged in v8go.
Make those steps conditional on the secret being provided.  This way nothing will need to be changed in the fork to workaround this problem.
=> Fix CI on forks by making the FOSSA step conditional on its secret

object.go, object_test.go
cc @wisepythagoras
https://github.com/rogchap/v8go/pull/145 is attempting to follow the current pattern of merging more code paths into `set`, which results in extra conditional complexity in `set` in order to essentially determine where it is called from and thus which argument to use.
The common functionality in the `set` function is value coercion, so just extract that to a separate function so that we can get rid of `set`.
Note that this makes all of these functions (coerceValue, Set, SetIdx) a lot more readable in isolation.  In contrast, the call site for `set` makes it unclear why the placeholder arguments are passed in and the `set` function is harder to understand without knowing the context in which it is called from.
=> refactor: Extract func coerceValue from set and remove func set

v8go.cc, v8go.h
There was a lot of use of void pointers because of the pointer types defined in v8go.h for the C API exposed to Go.  This results in a lot of use of static_cast, which is verbose and is less type safe (since the pointer could just as easily be cast to the wrong pointer type)
Forward declare the types in v8go.h without defining them, so Go will treat the pointers as pointers to opaque structs, but they will be pointers to the correct type in v8go.cc.
I couldn't do a forward declaration for `v8::Isolate` when compiling with C, so I used conditional compilation to just forward declare it for c++.  For C, we just want a distinct struct type for the pointer to help avoid mixing pointers.
I also moved `static_cast<m_ctx*>(iso->GetData(0))` to both reduce places where this static cast is done as …
=> Reduce unnecessary static casting of pointers received from Go

CHANGELOG.md, context.go, function_template.go, object_template.go, template.go, v8go.cc, v8go.h
We ran into fairly reproducible crashes from benchmarking code that was creating (and initializing) new isolates frequently, often in C.TemplateSetTemplate, where the value being set was a v8go.FunctionTemplate.  At first, I thought this might have been from a race condition from the finalizer running in a separate goroutine, which I thought was the reason other uses of finalizers was removed from v8go, but it happened even when the finalizer only freed the wrapper struct (m_template).  It looks like there was also a problem with the `template` becoming garbage after `template.ptr` is obtained from it, even before `template.ptr` is passed into the C function (e.g. `C.TemplateSetTemplate`).
To avoid the finalizer goroutine race condition, I changed the finalizer to only free the template …
=> Fix crashes from template finalizer

context.go, context_test.go, export_test.go, function.go, promise.go
This fixes an issue where you could not access function callbacks outside of `RunScript` since the context registry would not have been updated.
Fixes: https://github.com/rogchap/v8go/issues/186
=> Fix function callback usage outside of `RunScript`

context_test.go, function_test.go, helpers_test.go, object_test.go, value_test.go
The testing package has both t.Fail and t.Fatal, so calling the test helper method failIf makes it seem like it would call t.Fail and continue executing when it actually calls t.Fatal.
Renaming to fatalIf will make its behaviour clearer without looking at its implementation.
=> Rename failIf test helper to fatalIf since it uses t.Fatal

v8go.cc, v8go.h
There were a couple of places where C++ `new` was used in v8go.cc, then C.free was used on that pointer in Go.  
Mixing these is technically undefined behaviour, even though `new` and `delete` is often implemented as a wrapper around `malloc` and `free`
I used `malloc` to allocate these values so they can be safely freed using `C.free`.
Looks like clang-format was missed on the existing code in master, so using that produced some more noise to this change, but I isolated that to the second commit in this PR
=> Fix mismatched C free of memory allocated with C++ new

context_test.go, function_template_test.go, function_test.go, isolate_test.go, object_test.go
In order to address https://github.com/rogchap/v8go/issues/222, we need to avoid leaks in the tests as well as the code under test, since we currently depend on code using the library to dispose isolates and close contexts to avoid memory leaks.
This PR just adds the missing Isolate.Dispose and Context.Close calls that came up from using clang's address sanitizer.
=> Fix several leaks in tests

.github/workflows/test.yml, cgo.go, object.go, object_template.go, v8go.cc, v8go.h
It is easy to make some stupid mistakes that wastes some time debugging when the compiler could have pointer out the problem.  Using `-Wall` (with gcc/clang) will enable warnings for errors that compilers can detect.
I've addressed the existing warnings in the first few commits.  I enabled compiler warnings by default when compiling locally.  Additionally, I used `-Werror` to treat warnings as errors in CI.
I chose not to treat warnings as errors locally, mostly because of experience with lint like errors interrupting the development/debug feedback loop when they aren't really relevant.  Although, this is kind of a philosophical divergence from Go (e.g. how it warns about unused imports when adding in import "fmt" for debugging), so I can enable `-Werror` locally if other v8go devs …
=> Compile with warnings and fix exiting warnings

.github/workflows/leakcheck.yml, README.md, function_template_fetch_test.go, function_template_test.go, leak_test.go, leakcheck.go
Fixes #222
I added a separate workflow that does leaking, since it seems redundant to do on multiple platforms or go versions.  It also seemed simpler than adding conditionals to fit it into the existing test workflow.
I've tried using this locally on Linux and MacOS and have added some README documentation for doing leak checking locally.  I haven't tested on windows, but it looks like it currently isn't supported on windows (https://clang.llvm.org/docs/LeakSanitizer.html#supported-platforms)
=> Add Leak Check workflow to CI that uses Leak Sanitizer

CHANGELOG.md, isolate.go, isolate_test.go, v8go.cc, v8go.h
I've re-implemented the `ThrowException` function from #143, but added support for passing in a `Value` instead of just a string, as pointed out by @dylanahsmith. This allows us to pass a string, or forward in a `TypeError`.
A note: The return value is always `null` or `undefined`.
=> Add the ThrowException fn to the isolate

deps/build.py
build/deps.py was trying to import a script from v8, in a way that isn't python3 compatible, since there aren't __init__.py files in the directories on the path to the script
Use a separate command to execute the script, which is the way this is done in v8 as well (https://github.com/v8/v8/blob/ee74e718339223345b42935e9f4cbc7be208e557/DEPS#L552-L558).
=> Run v8 python script in a separate subshell

isolate_test.go, object_template_test.go
I also changed the test since it was originally for isolate garbage collection, which is no longer done, but is still useful for template garbage collection that is still done.
=> Remove useless print statement in a test

.github/workflows/fmt.yml, isolate_test.go, leak_test.go, script_compiler.go, v8go.cc, v8go.h
It is easy to forget to run `go fmt` or `go generate` to format the code.  This results in these changes ending up in following PRs and even get squashed into them due to the PRs being squash merged.
Add a CI step that will fail if the code wasn't formatted and show the missing format changes.
=> CI: Run gofmt and clang-format automatically on pull requests

CHANGELOG.md, errors.go, errors_test.go
I was debugging a syntax error and found that no location was being included when printing the JSError with `fmt.Printf("%+v\n", err)`, but that information was present in the struct's Location field.  It looks like this wasn't included in the StackTrace field that was used in JSError.Format, which may be because it isn't a runtime stack trace.
Use `err.StackTrace == err.Message` to detect when there is no runtime stack trace, then add the err.Location if it is present.
=> Include compile error location in verbose error message format

.github/workflows/v8build.yml, cgo.go, deps/linux_arm64/vendor.go
Follow up to https://github.com/rogchap/v8go/pull/202
Adds `linux/arm64` support
=> Build v8 for linux_arm64

CHANGELOG.md
@newhook pointed out the problem on slack
> I just figured out another upgrade issue I ran into...
> ```
> func (fn *Function) Call(args ...Valuer) (*Value, error) {
> ```
> Changed to:
> ```
> func (fn *Function) Call(recv Valuer, args ...Valuer) (*Value, error) {
> ```
> That is a bit of subtle breaking change since the code continues to compile, it just doesn't work like at all. I wonder if the release notes could make that little more obvious?
Add a couple more sentences to that changelog for that change to mention how old code will compile but the first argument would be reinterpreted and mention how to fix it.  Using the bold words **subtle breaking change** should help it stand out from other changes.
=> CHANGELOG: Highlight the subtlety of the Function Call breaking change

cgo.go
on darwin/x86_64 to compile linux/arm64 will be failed if "CXXFLAGS: ... -fpic ...", change the flag to "-fPIC" solved the problem.
=> change -fpic to -fPIC in cgo.go

v8go.cc
cc @GustavoCaso 
While reviewing https://github.com/Shopify/v8go/pull/39, I noticed that ExceptionError used
```
Locker locker(iso);
Isolate::Scope isolate_scope(iso);
```
even though ExceptionError isn't exported to Go code and the caller should already have taken the lock and entered that isolate scope.  That PR was trying to preserve this behaviour for existing code, but we should actually just remove those lines.
I've also made ExceptionError static, making it clearer that it isn't used outside that c file.
=> Remove unnecessary nested Locker and Isolate::Scope use

CHANGELOG.md, object.go, object_test.go
=> Fix Object.Set with an empty key string

context.go
The documentation on `Context.Isolate()` still referenced returning an `error`, which is no longer the case. This PR cleans that up.
=> Updating context documentation

cpuprofilenode.go, cpuprofiler.go, v8go.cc, v8go.h
Re: #283 
This PR adds the following additional values from [CPUProfileNode](https://v8docs.nodesource.com/node-16.15/d9/d6e/classv8_1_1_cpu_profile_node.html):
- [NodeId](https://v8docs.nodesource.com/node-16.15/d9/d6e/classv8_1_1_cpu_profile_node.html#a8ce3cb0b67b25227e68ef93944985fb7)
- [ScriptId](https://v8docs.nodesource.com/node-16.15/d9/d6e/classv8_1_1_cpu_profile_node.html#ac9332ecaea2232bdead05901522edc9d)
- [HitCount](https://v8docs.nodesource.com/node-16.15/d9/d6e/classv8_1_1_cpu_profile_node.html#afc9e7236aea6ea8e597016a74ce87eb6)
- [BailoutReason](https://v8docs.nodesource.com/node-16.15/d9/d6e/classv8_1_1_cpu_profile_node.html#ac562b6b67298941d139cd81dc2903d59)
Note: Since the ID's and hit counts are dynamic, I wasn't able to write tests around them. Let me know if anyone …
=> Add additional CPUProfile values

CHANGELOG.md, context.go, context_test.go, function_template.go, function_template_test.go, v8go.cc, v8go.h, value.go
This allows long-lived contexts that call go functions without leaking memory.  Typically, you'd want to use the following pattern for go functions that don't allow values to escape.
printfn := v8.NewFunctionTemplate(iso, func(info *v8.FunctionCallbackInfo) *v8.Value {
defer info.Release()
fmt.Printf("%+v\n", info.Args())
return nil
})
=> v8.Value becomes manually releaseable
